<a href="https://colab.research.google.com/github/ganeshkumar1887/DSA-in-java/blob/main/DL%20project/bank_churn_prediction/bank_churn_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy  as np

In [ ]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df.drop(columns = ['RowNumber','CustomerId','Surname'],inplace=True)

In [ ]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [ ]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [ ]:
df = pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)

In [ ]:
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False

In [ ]:
X = df.drop(columns=['Exited'])
y = df['Exited'].values

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_trf = scaler.fit_transform(X_train)
X_test_trf = scaler.transform(X_test)

In [ ]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model = Sequential()

model.add(Dense(11,activation='sigmoid',input_dim=11))
model.add(Dense(11,activation='sigmoid'))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
history = model.fit(X_train,y_train,batch_size=50,epochs=100,verbose=1,validation_split=0.2)

Epoch 1/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.7951 - loss: 0.5816 - val_accuracy: 0.7969 - val_loss: 0.5090
Epoch 2/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7884 - loss: 0.5172 - val_accuracy: 0.7969 - val_loss: 0.5013
Epoch 3/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7993 - loss: 0.4988 - val_accuracy: 0.7969 - val_loss: 0.4992
Epoch 4/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7940 - loss: 0.5053 - val_accuracy: 0.7969 - val_loss: 0.4983
Epoch 5/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7843 - loss: 0.5182 - val_accuracy: 0.7969 - val_loss: 0.4977
Epoch 6/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7938 - loss: 0.5043 - val_accuracy: 0.7969 - val_loss: 0.4972
Epoch 7/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7970 - loss: 0.4998 - val_accuracy: 0.7969 - val_loss: 0.4971
Epoch 8/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8042 - loss: 0.4907 - val_accuracy: 0.7969 - val_loss: 0.4970
Epoch 9/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7967 - loss: 0.4992 - val_accuracy: 0.7969 - val_loss: 0.4966
Epoch 10/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7972 - loss: 0.4997 - val_accuracy: 0.7969 - val_loss: 0.4965
Epoch 11/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8007 - loss: 0.4945 - val_accuracy: 0.7969 - val_loss: 0.4964
Epoch 12/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7920 - loss: 0.5062 - val_accuracy: 0.7969 - val_loss: 0.4963
Epoch 13/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7956 - loss: 0.5014 - val_accuracy: 0.7969 - val_loss: 0.4961
Epoch 14/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8003 - loss: 0.4953 - val_accuracy: 0.7969 - val_loss: 0.4960
Epoch 15/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7917 - loss: 0.5047 - val_accuracy: 0.7969 - val_loss: 0.4959
Epoch 16/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8013 - loss: 0.4940 - val_accuracy: 0.7969 - val_loss: 0.4958
Epoch 17/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7902 - loss: 0.5073 - val_accuracy: 0.7969 - val_loss: 0.4957
Epoch 18/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8019 - loss: 0.4903 - val_accuracy: 0.7969 - val_loss: 0.4958
Epoch 19/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7964 - loss: 0.5004 - val_accuracy: 0.7969 - val_loss: 0.4956
Epoch 20/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7996 - loss: 0.4948 - val_accuracy: 0.7969 - val_loss: 0.4955
Epoch 21/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7983 - loss: 0.4939 - val_accuracy: 0.7969 - val_loss: 0.4955
Epoch 22/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7948 - loss: 0.5008 - val_accuracy: 0.7969 - val_loss: 0.4954
Epoch 23/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7955 - loss: 0.4997 - val_accuracy: 0.7969 - val_loss: 0.4955
Epoch 24/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7925 - loss: 0.5030 - val_accuracy: 0.7969 - val_loss: 0.4954
Epoch 25/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7888 - loss: 0.5070 - val_accuracy: 0.7969 - val_loss: 0.4956
Epoch 26/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8005 - loss: 0.4940 - val_accuracy: 0.7969 - val_loss: 0.4957
Epoch 27/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7901 - loss: 0.5081 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 28/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7901 - loss: 0.5054 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 29/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7960 - loss: 0.4976 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 30/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7973 - loss: 0.4955 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 31/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7964 - loss: 0.4991 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 32/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7895 - loss: 0.5076 - val_accuracy: 0.7969 - val_loss: 0.4954
Epoch 33/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7962 - loss: 0.4970 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 34/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7898 - loss: 0.5093 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 35/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7905 - loss: 0.5066 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 36/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7897 - loss: 0.5062 - val_accuracy: 0.7969 - val_loss: 0.4951
Epoch 37/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7977 - loss: 0.4956 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 38/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7989 - loss: 0.4943 - val_accuracy: 0.7969 - val_loss: 0.4956
Epoch 39/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7983 - loss: 0.4959 - val_accuracy: 0.7969 - val_loss: 0.4951
Epoch 40/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7972 - loss: 0.4968 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 41/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8008 - loss: 0.4935 - val_accuracy: 0.7969 - val_loss: 0.4954
Epoch 42/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7913 - loss: 0.5058 - val_accuracy: 0.7969 - val_loss: 0.4951
Epoch 43/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7902 - loss: 0.5074 - val_accuracy: 0.7969 - val_loss: 0.4951
Epoch 44/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7935 - loss: 0.5016 - val_accuracy: 0.7969 - val_loss: 0.4951
Epoch 45/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7986 - loss: 0.4951 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 46/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8026 - loss: 0.4910 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 47/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7959 - loss: 0.4984 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 48/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5041 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 49/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8004 - loss: 0.4927 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 50/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8008 - loss: 0.4913 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 51/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7956 - loss: 0.4969 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 52/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8029 - loss: 0.4875 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 53/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7970 - loss: 0.5013 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 54/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7986 - loss: 0.4957 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 55/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7983 - loss: 0.4958 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 56/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7862 - loss: 0.5103 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 57/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7929 - loss: 0.5022 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 58/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7963 - loss: 0.5001 - val_accuracy: 0.7969 - val_loss: 0.4954
Epoch 59/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8004 - loss: 0.4895 - val_accuracy: 0.7969 - val_loss: 0.4954
Epoch 60/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8028 - loss: 0.4889 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 61/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7956 - loss: 0.5004 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 62/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7950 - loss: 0.4995 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 63/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7934 - loss: 0.5023 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 64/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7977 - loss: 0.4961 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 65/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7915 - loss: 0.5038 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 66/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8041 - loss: 0.4890 - val_accuracy: 0.7969 - val_loss: 0.4954
Epoch 67/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8025 - loss: 0.4915 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 68/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7964 - loss: 0.4967 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 69/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8003 - loss: 0.4934 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 70/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.4979 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 71/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7888 - loss: 0.5093 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 72/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7954 - loss: 0.4994 - val_accuracy: 0.7969 - val_loss: 0.4957
Epoch 73/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7920 - loss: 0.5046 - val_accuracy: 0.7969 - val_loss: 0.4954
Epoch 74/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8012 - loss: 0.4923 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 75/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7946 - loss: 0.5000 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 76/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7892 - loss: 0.5059 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 77/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7936 - loss: 0.5027 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 78/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7971 - loss: 0.4965 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 79/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7951 - loss: 0.4998 - val_accuracy: 0.7969 - val_loss: 0.4954
Epoch 80/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7951 - loss: 0.4989 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 81/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7921 - loss: 0.5029 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 82/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7975 - loss: 0.4962 - val_accuracy: 0.7969 - val_loss: 0.4954
Epoch 83/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7963 - loss: 0.4961 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 84/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7978 - loss: 0.4949 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 85/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7951 - loss: 0.5006 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 86/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7994 - loss: 0.4918 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 87/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7947 - loss: 0.5017 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 88/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8024 - loss: 0.4879 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 89/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8001 - loss: 0.4931 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 90/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7937 - loss: 0.5014 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 91/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8008 - loss: 0.4938 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 92/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7939 - loss: 0.4991 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 93/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7985 - loss: 0.4941 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 94/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7907 - loss: 0.5047 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 95/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7987 - loss: 0.4955 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 96/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8008 - loss: 0.4918 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 97/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7988 - loss: 0.4923 - val_accuracy: 0.7969 - val_loss: 0.4953
Epoch 98/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8035 - loss: 0.4901 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 99/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7944 - loss: 0.5010 - val_accuracy: 0.7969 - val_loss: 0.4952
Epoch 100/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7978 - loss: 0.4970 - val_accuracy: 0.7969 - val_loss: 0.4951

In [ ]:
y_pred = model.predict(X_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

In [ ]:
y_pred

array([[0.25121894],
       [0.25121894],
       [0.23267166],
       ...,
       [0.23267166],
       [0.28767893],
       [0.25121894]], dtype=float32)

In [ ]:
y_pred = y_pred.argmax(axis=-1)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7975